version: "3.8"

services:
  react-frontend:
    image: quick_care_image:latest   # Using the image you already built
    container_name: react-frontend
    ports:
      - "3000:80"   # Access at http://localhost:3000
    restart: always
